name: StreamRoller apidocs

on:
  workflow_dispatch:
  workflow_call:
env:
  #MY_API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  GITHUB_TOKEN: ${{ github.token }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.16.0"
      - name: Install npm dependencies
        run: |
          cd docs
          cd apidocs
          npm install
      - name: Clean old docs
        run: |
          cd docs
          cd apidocs
          pwd
          rm -fr public/*
      - name: Run build task
        run: |
          cd docs
          cd apidocs
          npm run builddocslinux
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "docs/apidocs/public/"
          REMOTE_HOST: ${{ secrets.ORACLE_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.ORACLE_REMOTE_USER }}
          TARGET: ${{ secrets.ORACLE_REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
