# trigger on the cix.x.x tag.
name: CI process chain
run-name: ${{ github.actor }} running CI process on cix.x.x tag creation
on:
  workflow_dispatch:
  push:
    tags:
      - "ci*.*.*"
#env:
#MY_API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#VERSION_TAG: ${{ github.GITHUB_REF_NAME }}
jobs:
  creating_readmes:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: npm install
        run: npm install
      - name: note time to check it was built later
        run: cat extensions/chatbot/README.md
      - name: running node readmebuilder.mjs
        run: |
          cd docs/apidocs
          node readmebuilder.mjs
      - name: check timestamp for update
        run: |
          pwd
          cat ../../extensions/chatbot/README.md
          cat extensions/chatbot/README.md
