# trigger on the cix.x.x tag.
name: CI process chain
run-name: ${{ github.actor }} running CI process on cix.x.x tag creation
on:
  workflow_dispatch:
  push:
    tags:
      - "ci*.*.*"
env:
  VERSION_TAG: ${{ github.ref_name }}
  #VERSION_TAG: ci1.1.1
jobs:
  createReadMe:
    uses: ./.github/workflows/create_readmes.yml
  createReleaseTag:
    runs-on: windows-latest
    needs: createReadMe
    outputs:
      tag_name: ${{ steps.increment_version.outputs.NEW_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Increment Patch Version
        id: increment_version
        run: |
          $version = "${{ env.VERSION_TAG }}"
          $newVersion = "$version".replace("ci","v")
          Write-Output "Generated Tag: $newVersion"
          "NEW_VERSION=$newVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "NEW_VERSION=$newVersion" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        shell: pwsh
      - name: test output
        run: |
          echo "VERSION_TAG is ${{env.VERSION_TAG}}"
          echo "NEW_VERSION is ${{env.NEW_VERSION}}"
        shell: pwsh

      - name: Pushing tag to repo
        run: |
          echo "Pushing TAG ${{env.NEW_VERSION}}"
          git tag ${{env.NEW_VERSION}}
          git push origin --tags
        shell: pwsh
  BuildRelease:
    needs: createReleaseTag
    uses: ./.github/workflows/create_release.yml
    with:
      tag: ${{ needs.createReleaseTag.outputs.tag_name }}
  UpdateDocs:
    needs: createReleaseTag
    uses: ./.github/workflows/build_docs.yml
    with:
      tag: ${{ needs.createReleaseTag.outputs.tag_name }}
    secrets: inherit
