# trigger on the cix.x.x tag.
name: CI process chain
run-name: ${{ github.actor }} running CI process on cix.x.x tag creation
on:
  workflow_dispatch:
  push:
    tags:
      - "ci*.*.*"
env:
  #MY_API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #VERSION_TAG: ${{ github.ref_name }}
  VERSION_TAG: ci1.1.1
jobs:
  createReadMe:
    uses: ./.github/workflows/create_readmes.yml
  createRelease:
    runs-on: windows-latest
    steps:
      - name: Increment Patch Version
        id: increment_version
        run: |
          $version = "${{ env.VERSION_TAG }}"
          $parts = $version -split "\."
          $major = $parts[0]
          $minor = $parts[1]
          $patch = [int]$parts[2] + 1
          $newVersion = "$major.$minor.$patch".replace("ci","re")
          #echo "New version: $newVersion"
          #echo $Env:NEW_VERSION = $newVersion
          #echo "VERSION_TAG is ${{env.VERSION_TAG}}"
          echo "NEW_VERSION=$newVersion" >> $env:GITHUB_ENV
        shell: pwsh
      - name: test output
        run: |
          echo "VERSION_TAG is ${{env.VERSION_TAG}}"
          echo "NEW_VERSION is ${{env.NEW_VERSION}}"
        shell: pwsh

      - name: Save New Version
        run: |
          echo "Pushing TAG ${{env.NEW_VERSION}}"
          git tag ${{env.NEW_VERSION}}
          git push
        shell: pwsh
