name: create_windows_exe
run-name: ${{ github.actor }} is Creating a windows version of Streamroller
on: [push]

jobs:
  create_windows-version:
    runs-on: windows-latest
    env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
      - run: npm install
      - run: npm i -D caxa
      - run: cd backend && npm install
      - run: npx caxa -i . -o StreamRoller.exe -- "{{caxa}}/node_modules/.bin/node" -- "{{caxa}}\backend\data_center\server.js"
      - uses: dmnemec/copy_file_to_another_repo_action@main
      - with:
          source_file: 'StreamRoller.exe'
          destination_repo: 'SilenusTA/StreamRollerRelease'
          destination_folder: 'windows_releases'
          user_email: 'silenusta@gmail.com'
          user_name: 'silenusTA'
          commit_message: 'Software Release'
      
