# trigger on the cix.x.x tag.
name: CI process chain
run-name: ${{ github.actor }} running CI process on cix.x.x tag creation
on:
  workflow_dispatch:
  workflow_call:
env:
  #MY_API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #VERSION_TAG: ${{ github.ref_name }}
  VERSION_TAG: ci0.0.0
jobs:
  creating_readmes:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: npm install
        run: npm install
      - name: note time to check it was built later
        run: more .\extensions\users\README.md
      - name: running node readmebuilder.mjs
        run: |
          cd docs/apidocs
          node readmebuilder.mjs
      - name: check timestamp for update
        run: |
          dir
          more extensions\users\README.md
      - name: adding files to git
        run: |
          foreach($line in Get-Content .\filelist.txt) {if($line -match $regex){git add $line}}
          git commit -m "autodoc readme update"
          git push
