name: Creating a new Release
run-name: ${{ github.actor }} delivering exe to live repo release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
env:
  MY_API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  VERSION_TAG: ${{ github.GITHUB_REF_NAME }}
jobs:
  minify_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.13.2'
    - name: minifying
      uses: nizarmah/auto-minify@v2.1
      with:
        overwrite: true
        js_engine : 'uglify-js'
    - name: removing git folder (to keep space down in exe)
      run: |
          ls -la
          rm -fr .git/*
          rmdir .git
          ls -la
    - name: uploading artifact
      uses: actions/upload-artifact@v3
      with:
        name: mini-artifacts
        path: .      
  creating_exe:
    runs-on: windows-latest    
    needs: minify_code
    steps:
    - name: importing artecfact
      uses: actions/download-artifact@v3
      with:
        name: mini-artifacts
    - uses: actions/setup-node@v3
      with:
        node-version: '16.13.2'
    - name: Creating exe
      run: |
          cat extensions/chatbot/chatbot.js
          npm i -D caxa
          npm install
          npx caxa -m "First run, unpacking " -i . -o StreamRoller.exe -- "{{caxa}}/node_modules/.bin/node" -- "{{caxa}}/backend/data_center/server.js"
    - name: Create Release.txt
      run: |
          echo Release version ${{ github.ref_name }} >> Release.txt
    - name: Zip up exe
      run: |
        7z a StreamRoller.zip StreamRoller.exe
    - name: Push Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        body: Version ${{ github.ref_name }} of StreamRoller
        name: "StreamRoller${{ github.ref_name }}"
        tag_name: ${{ github.ref_name }}
        token: ${{secrets.API_TOKEN_GITHUB}}
        repository: SilenusTA/StreamRoller
        files: |
          Release.txt
          StreamRoller.zip
          StreamRoller.exe
