name: Create a new Release
run-name: ${{ github.actor }} delivering exe to live repo release
on:
  push:
    tags:
      - "v*.*.*"
env:
  MY_API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  VERSION_TAG: ${{ github.GITHUB_REF_NAME }}
jobs:
  minify_code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: minifying
      uses: nizarmah/auto-minify@v2.1
      with:
        overwrite: true
        js_engine : 'uglify-js'
    - name: removing git folder (to keep space down in exe)
      run: |
          ls -la
          rm -fr .git/*
          rmdir .git
          ls -la
    - name: uploading artifact
      uses: actions/upload-artifact@v3
      with:
        name: mini-artifacts
        path: .      
  creating_exe:
    runs-on: windows-latest    
    needs: minify_code
    steps:
    - name: importing artecfact
      uses: actions/download-artifact@v3
      with:
        name: mini-artifacts
    - uses: actions/setup-node@v3
      with:
        node-version: '18.6.0'
    - name: Create Version.txt
      run: |
          echo ${{ github.ref_name }} > SoftwareVersion.txt
    - name: Creating exe
      run: |
          npm i -D caxa
          npm install
          npx caxa -m "Unpacking " -i . -o StreamRoller${{ github.ref_name }}.exe -- "{{caxa}}/install.cmd" "{{caxa}}"
    - name: Create Release.txt
      run: |
          echo Release version ${{ github.ref_name }} >> Release.txt
    - name: Zip up exe
      run: |
        7z a StreamRoller${{ github.ref_name }}.zip StreamRoller${{ github.ref_name }}.exe
    - name: Push Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        body: Version ${{ github.ref_name }} of StreamRoller
        name: "StreamRoller${{ github.ref_name }}"
        tag_name: ${{ github.ref_name }}
        token: ${{secrets.API_TOKEN_GITHUB}}
        repository: SilenusTA/StreamRoller
        files: |
          Release.txt
          StreamRoller${{ github.ref_name }}.zip
          StreamRoller${{ github.ref_name }}.exe
