name: minify_and_upload
run-name: ${{ github.actor }} is minifying
on: workflow_dispatch

jobs:
  minify_and_Build:
    runs-on: ubuntu-latest
    env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '16.13.2'
      - uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
          js_engine : 'uglify-js'
      - run: |
            export GIT_TRACE_PACKET=1
            export GIT_TRACE=1
            export GIT_CURL_VERBOSE=1
            git config --unset-all http.https://github.com/.extraheader
            git config http.postBuffer 524288000
            git config --global user.email "silenusta@gmail.com"
            git config --global user.name "silenusta"
            git config --global credential.helper cache
            git remote rename origin upstream
            git remote add origin https://${{secrets.API_TOKEN_GITHUB}}@github.com/SilenusTA/StreamRoller
            git commit -m "$(date)"
            git push --no-thin origin master

            
#            ls
#            git clone https://${{secrets.API_TOKEN_GITHUB}}@github.com/SilenusTA/StreamRoller ./tmp
#            ls
#            rm -fr .git/*
#            rmdir .git
#            mv tmp/.git .git
#            ls
#            git add .
#
#            git commit -m "$(date)"
#            git push 

#            git tag -a ${{GITHUB_REF_NAME}} -m "Autmated Build"
 

