name: minify_and_Build
run-name: ${{ github.actor }} is minifying
on: [push]

jobs:
  minify_and_Build:
    runs-on: ubuntu-latest
    env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
      - uses: nizarmah/auto-minify@v2.1
        with:
          js_engine : 'uglify-js'
          overwrite: true
      - run: |
            npm i -D caxa
            npm install
            cat extensions/chatbot/chatbot.js
#npm start

