name: Test release build
run-name: ${{ github.actor }} Testing exe Build
on:
  workflow_dispatch:
env:
  MY_API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  VERSION_TAG: ${{ github.GITHUB_REF_NAME }}
jobs:
  remove_git:
    runs-on: ubuntu-latest
    steps:
    - name: getting node version
      run: node -v
    - uses: actions/checkout@v20
    - name: removing git folder (to keep space down in exe)
      run: |
          ls -la
          rm -fr .git/*
          rmdir .git
          ls -la
    - name: uploading artifact
      uses: actions/upload-artifact@v4
      with:
        name: mini-artifacts
        path: .      
  creating_exe:
    runs-on: windows-latest  
    needs: remove_git  
    steps:
    - name: importing artecfact
      uses: actions/download-artifact@v4
      with:
        name: mini-artifacts
    - uses: actions/setup-node@v20
      #with:
        #node-version: '18.6.0'
    - name: Create SoftwareVersion.txt
      run: |
          echo "TESTBUILD #${{github.run_number}}.${{ github.run_attempt }}" > SoftwareVersion.txt
          dir S*
          type SoftwareVersion.txt
    - name: Creating exe
      run: |
          npm i -D caxa
          npm install
          npx caxa -m "Unpacking " -i . -o StreamRoller${{ github.ref_name }}.exe -- "{{caxa}}/install.cmd" "{{caxa}}"
    - name: Create Release.txt
      run: |
          echo Release version ${{ github.ref_name }} >> Release.txt
    - name: Zip up exe
      run: |
        7z a StreamRoller${{ github.ref_name }}.zip StreamRoller${{ github.ref_name }}.exe
    - name: uploading artifact
      uses: actions/upload-artifact@v3
      with:
        name: StreamRoller${{ github.ref_name }}.zip
        path: StreamRoller${{ github.ref_name }}.exe
